services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=socialhub'
      - 'MYSQL_ROOT_PASSWORD=admin'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: