CREATE TABLE `socialhub`.`token_auditoria` (
TOKEN         VARCHAR(200) NOT NULL,
IDUSUARIO     BIGINT NOT NULL,
DTINICIO      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DTFIM         TIMESTAMP,
IS_USADO      VARCHAR(10) DEFAULT 'NAO',
PRIMARY KEY (TOKEN),
FOREIGN KEY (IDUSUARIO) REFERENCES `socialhub`.`usuario`(IDUSUARIO)
);
