CREATE TABLE `socialhub`.`token_invite` (
    TOKEN         VARCHAR(200) NOT NULL,
    IDUSUARIO     BIGINT NOT NULL,
    IDSPACE       BIGINT NOT NULL,
    IDCARGO       BIGINT NOT NULL,
    DTINICIO      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DTFIM         TIMESTAMP NOT NULL,
    STATUS        VARCHAR(10) NOT NULL,
    PRIMARY KEY (TOKEN),
    FOREIGN KEY (IDUSUARIO) REFERENCES `socialhub`.`usuario`(IDUSUARIO),
    FOREIGN KEY (IDSPACE) REFERENCES `socialhub`.`space`(IDSPACE)
);
