ALTER TABLE `socialhub`.`conta`
    ADD COLUMN STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'; -- Para o enum StatusConta

ALTER TABLE `socialhub`.`conta`
    ADD CONSTRAINT UNIQUE_CONTA_REDESOCIAL
        UNIQUE (IDSPACE, IDREDESOCIAL, STATUS);
